[General]
background=assets/background.jpg
middleOverlay=assets/middleOverlay.png
foreground=assets/foreground.png
font_time="steelfish outline regular"
font_general="SF Pro Display Bold"
text_color="#b3ffffff"
